import { Roadmap, Project, AffiliateResource } from '@/types/blog';

export const roadmaps: Roadmap[] = [
  {
    title: 'Full-Stack Developer',
    description: 'A practical, opinionated full-stack developer roadmap for 2026. Learn HTML, CSS, JavaScript, TypeScript, React, Next.js, APIs, databases, authentication, testing, and DevOps by building production-style projects.',
    modules: '10 modules',
    duration: '8-12 months',
    status: 'published',
    slug: 'full-stack-developer',
  },
  {
    title: 'AI Engineer',
    description: 'A step-by-step AI Engineer roadmap for 2026. Learn Python, Machine Learning, Deep Learning, LLMs, LangChain, RAG, MLOps, and Agentic AI — built from real production experience.',
    modules: '8 modules',
    duration: '6-8 months',
    status: 'published',
    slug: 'ai-engineer',
  },
  {
    title: 'DevOps',
    description: 'Cloud infrastructure, CI/CD, observability, and platform reliability.',
    modules: 'TBD',
    duration: 'TBD',
    status: 'coming-soon',
  },
];

export const projects: Project[] = [
  {
    title: 'AI-Powered Task Manager',
    description: 'Full-stack app with AI assistant and real-time collaboration',
    tech: ['Next.js', 'FastAPI', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1557426272-fc759fdf7a8d?w=600&q=80',
    github: 'https://github.com/myousafmarfani',
  },
  {
    title: 'Multi-Agent Emergency Response',
    description: 'Coordinated AI agents for emergency handling',
    tech: ['Python', 'LangChain', 'React'],
    image: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=600&q=80',
    github: 'https://github.com/myousafmarfani',
  },
  {
    title: 'Real-time Analytics Dashboard',
    description: 'Live data visualization with WebSocket connections',
    tech: ['Next.js', 'Socket.io', 'MongoDB'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    github: 'https://github.com/myousafmarfani',
  },
];

export const affiliateResources: AffiliateResource[] = [
  {
    name: 'freeCodeCamp',
    category: 'Learning Platforms',
    description: 'Interactive curriculum with projects, certifications, and a large community.',
    price: 'Free',
    discount: 'Open access',
    features: ['Full-stack path', 'Hands-on projects', 'Certifications'],
    link: 'https://www.freecodecamp.org/',
  },
  {
    name: 'Coursera',
    category: 'Learning Platforms',
    description: 'University and industry courses with guided projects and certificates.',
    price: 'Free + Paid',
    discount: 'Financial aid',
    features: ['Degree tracks', 'Professional certificates', 'Guided projects'],
    link: 'https://www.coursera.org/',
  },
  {
    name: 'edX',
    category: 'Learning Platforms',
    description: 'Courses and programs from top universities with flexible pacing.',
    price: 'Free + Paid',
    discount: 'Audit option',
    features: ['MicroMasters', 'Professional certificates', 'Self-paced'],
    link: 'https://www.edx.org/',
  },
  {
    name: 'Frontend Masters',
    category: 'Learning Platforms',
    description: 'Deep-dive frontend and full-stack workshops by industry experts.',
    price: 'Paid',
    discount: 'Team plans',
    features: ['Expert-led courses', 'Workshop format', 'Modern frameworks'],
    link: 'https://frontendmasters.com/',
  },
  {
    name: 'Vercel',
    category: 'Deployment Clouds',
    description: 'Frontend cloud for fast builds, previews, and edge delivery.',
    price: 'Free + Paid',
    discount: 'Hobby plan',
    features: ['Preview deployments', 'Edge functions', 'CI/CD'],
    link: 'https://vercel.com/',
  },
  {
    name: 'Netlify',
    category: 'Deployment Clouds',
    description: 'Deploy web projects with automated builds and serverless functions.',
    price: 'Free + Paid',
    discount: 'Starter tier',
    features: ['Git-based deploys', 'Forms', 'Serverless'],
    link: 'https://www.netlify.com/',
  },
  {
    name: 'Render',
    category: 'Deployment Clouds',
    description: 'Full-stack hosting for web apps, APIs, and background jobs.',
    price: 'Free + Paid',
    discount: 'Free web services',
    features: ['Auto deploys', 'Postgres', 'Private networking'],
    link: 'https://render.com/',
  },
  {
    name: 'Fly.io',
    category: 'Deployment Clouds',
    description: 'Run applications globally with low-latency edge regions.',
    price: 'Free + Paid',
    discount: 'Free allowance',
    features: ['Global regions', 'WireGuard VPN', 'Volumes'],
    link: 'https://fly.io/',
  },
  {
    name: 'Visual Studio Code',
    category: 'Developer Tools',
    description: 'Powerful editor with extensions, debugging, and Git integration.',
    price: 'Free',
    discount: 'Open-source',
    features: ['Extensions', 'Debugger', 'Remote dev'],
    link: 'https://code.visualstudio.com/',
  },
  {
    name: 'GitHub',
    category: 'Developer Tools',
    description: 'Code hosting, CI/CD automation, and collaboration workflows.',
    price: 'Free + Paid',
    discount: 'Student pack',
    features: ['Pull requests', 'Actions CI', 'Issues and projects'],
    link: 'https://github.com/',
  },
  {
    name: 'Docker',
    category: 'Developer Tools',
    description: 'Container tooling for consistent dev and production environments.',
    price: 'Free + Paid',
    discount: 'Open-source',
    features: ['Containers', 'Compose', 'Desktop app'],
    link: 'https://www.docker.com/',
  },
  {
    name: 'Postman',
    category: 'Developer Tools',
    description: 'API platform for testing, documentation, and collaboration.',
    price: 'Free + Paid',
    discount: 'Free team tier',
    features: ['API client', 'Collections', 'Mock servers'],
    link: 'https://www.postman.com/',
  },
  {
    name: 'PostgreSQL',
    category: 'Databases',
    description: 'Reliable open-source relational database with rich extensions.',
    price: 'Free',
    discount: 'Open-source',
    rating: 0,
    features: ['SQL compliance', 'Extensions', 'Strong community'],
    link: 'https://www.postgresql.org/',
  },
  {
    name: 'Supabase',
    category: 'Databases',
    description: 'Postgres platform with auth, storage, and realtime APIs.',
    price: 'Free + Paid',
    discount: 'Free tier',
    features: ['Auth', 'Storage', 'Realtime'],
    link: 'https://supabase.com/',
  },
  {
    name: 'PlanetScale',
    category: 'Databases',
    description: 'Serverless MySQL platform with branching workflows.',
    price: 'Free + Paid',
    discount: 'Free tier',
    features: ['Branching', 'Online migrations', 'Scalable'],
    link: 'https://planetscale.com/',
  },
  {
    name: 'MongoDB Atlas',
    category: 'Databases',
    description: 'Managed MongoDB with global clusters and automated backups.',
    price: 'Free + Paid',
    discount: 'Free tier',
    features: ['Auto scaling', 'Backups', 'Multi-cloud'],
    link: 'https://www.mongodb.com/atlas',
  },
];
